# Generated by Django 5.1.6 on 2025-04-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatchManagement',
            new_name='Patching',
        ),
    ]
