# Generated by Django 5.1.6 on 2025-03-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='cpu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='local_disk',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.FloatField(),
        ),
    ]
