# Generated by Django 5.1.6 on 2025-04-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_patching_device_id_alter_patching_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patching',
            unique_together={('Laptop', 'device_id', 'hotfixid', 'description', 'installedOn')},
        ),
    ]
