# Generated by Django 5.1.6 on 2025-03-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_deviceperformance_cpu_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceperformance',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceperformance',
            name='disk_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceperformance',
            name='ram_usage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
