# Generated by Django 5.1.6 on 2025-04-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_patching_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotfixid', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('category', models.CharField(choices=[('Security', 'Security'), ('Feature', 'Feature'), ('Bug Fix', 'Bug Fix'), ('Cumulative', 'Cumulative Updates'), ('other', 'Other')], max_length=50)),
                ('affected_os', models.TextField()),
                ('download_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
