# Generated by Django 5.1.6 on 2025-03-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_laptop_bitlocker_enabled_alter_laptop_cpu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='ram',
        ),
        migrations.AlterField(
            model_name='deviceperformancehistory',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceperformancehistory',
            name='disk_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceperformancehistory',
            name='ram_usage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
