# Generated by Django 5.1.6 on 2025-04-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_windowupdatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowupdatehistory',
            name='os_build',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
