# Generated by Django 5.1.6 on 2025-03-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_remove_laptop_ram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceperformance',
            old_name='disk_usage',
            new_name='disk_free',
        ),
        migrations.RenameField(
            model_name='deviceperformance',
            old_name='ram_usage',
            new_name='ram_free',
        ),
        migrations.RenameField(
            model_name='deviceperformancehistory',
            old_name='disk_usage',
            new_name='disk_available',
        ),
        migrations.RenameField(
            model_name='deviceperformancehistory',
            old_name='ram_usage',
            new_name='ram_available',
        ),
    ]
