# Generated by Django 5.1.6 on 2025-04-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_windowupdatehistory_os_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patching',
            name='installedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
