# Generated by Django 5.1.6 on 2025-03-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_rename_disk_usage_deviceperformance_disk_free_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceperformancehistory',
            old_name='disk_available',
            new_name='disk_free',
        ),
        migrations.RenameField(
            model_name='deviceperformancehistory',
            old_name='ram_available',
            new_name='ram_free',
        ),
    ]
