# Generated by Django 5.1.6 on 2025-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_patching_installedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patching',
            name='installedOn',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
