# Generated by Django 5.1.6 on 2025-03-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_rename_disk_available_deviceperformancehistory_disk_free_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='manufacturer',
            new_name='hostname',
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
