# Generated by Django 5.1.6 on 2025-03-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_rename_manufacturer_laptop_hostname_laptop_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceperformance',
            name='network_receive',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceperformance',
            name='network_sent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
