# Generated by Django 5.1.6 on 2025-03-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_deviceperformance_network_receive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='bitlocker_enabled',
            new_name='bitlocker',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='domain_joined',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='onedrive_enabled',
            new_name='onedrive',
        ),
    ]
