# Generated by Django 5.1.6 on 2025-03-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_rename_bitlocker_enabled_laptop_bitlocker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
