# Generated by Django 5.1.6 on 2025-03-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_laptop_username_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='cpu',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
