# Generated by Django 5.1.6 on 2025-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_laptop_cpu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='vpn_enabled',
            new_name='vpn',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='os',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='serial_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
