# Generated by Django 5.1.6 on 2025-03-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_rename_vpn_enabled_laptop_vpn_alter_laptop_os_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceperformance',
            old_name='network_receive',
            new_name='receive_bytes',
        ),
        migrations.RenameField(
            model_name='deviceperformance',
            old_name='network_sent',
            new_name='sent_bytes',
        ),
    ]
