# Generated by Django 5.1.6 on 2025-03-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_rename_network_receive_deviceperformance_receive_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceperformance',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deviceperformance',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
